name: dockerpostgis

services:

  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgis
  postgis:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=mypassword
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: "PGPASSWORD=mypassword pg_isready -h 127.0.0.1 -U postgres -d postgres"

  
volumes:
  pgdata:

  